/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVacunasRouteImport } from './routes/_authenticated/vacunas'
import { Route as AuthenticatedAnimalesIndexRouteImport } from './routes/_authenticated/animales.index'
import { Route as AuthenticatedVacasNumeroRouteImport } from './routes/_authenticated/vacas.$numero'
import { Route as AuthenticatedAnimalesNumeroRouteImport } from './routes/_authenticated/animales.$numero'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVacunasRoute = AuthenticatedVacunasRouteImport.update({
  id: '/vacunas',
  path: '/vacunas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnimalesIndexRoute =
  AuthenticatedAnimalesIndexRouteImport.update({
    id: '/animales/',
    path: '/animales/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVacasNumeroRoute =
  AuthenticatedVacasNumeroRouteImport.update({
    id: '/vacas/$numero',
    path: '/vacas/$numero',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnimalesNumeroRoute =
  AuthenticatedAnimalesNumeroRouteImport.update({
    id: '/animales/$numero',
    path: '/animales/$numero',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vacunas': typeof AuthenticatedVacunasRoute
  '/animales/$numero': typeof AuthenticatedAnimalesNumeroRoute
  '/vacas/$numero': typeof AuthenticatedVacasNumeroRoute
  '/animales/': typeof AuthenticatedAnimalesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vacunas': typeof AuthenticatedVacunasRoute
  '/': typeof AuthenticatedIndexRoute
  '/animales/$numero': typeof AuthenticatedAnimalesNumeroRoute
  '/vacas/$numero': typeof AuthenticatedVacasNumeroRoute
  '/animales': typeof AuthenticatedAnimalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/vacunas': typeof AuthenticatedVacunasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/animales/$numero': typeof AuthenticatedAnimalesNumeroRoute
  '/_authenticated/vacas/$numero': typeof AuthenticatedVacasNumeroRoute
  '/_authenticated/animales/': typeof AuthenticatedAnimalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/vacunas'
    | '/animales/$numero'
    | '/vacas/$numero'
    | '/animales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/vacunas'
    | '/'
    | '/animales/$numero'
    | '/vacas/$numero'
    | '/animales'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/vacunas'
    | '/_authenticated/'
    | '/_authenticated/animales/$numero'
    | '/_authenticated/vacas/$numero'
    | '/_authenticated/animales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vacunas': {
      id: '/_authenticated/vacunas'
      path: '/vacunas'
      fullPath: '/vacunas'
      preLoaderRoute: typeof AuthenticatedVacunasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/animales/': {
      id: '/_authenticated/animales/'
      path: '/animales'
      fullPath: '/animales/'
      preLoaderRoute: typeof AuthenticatedAnimalesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vacas/$numero': {
      id: '/_authenticated/vacas/$numero'
      path: '/vacas/$numero'
      fullPath: '/vacas/$numero'
      preLoaderRoute: typeof AuthenticatedVacasNumeroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/animales/$numero': {
      id: '/_authenticated/animales/$numero'
      path: '/animales/$numero'
      fullPath: '/animales/$numero'
      preLoaderRoute: typeof AuthenticatedAnimalesNumeroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedVacunasRoute: typeof AuthenticatedVacunasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnimalesNumeroRoute: typeof AuthenticatedAnimalesNumeroRoute
  AuthenticatedVacasNumeroRoute: typeof AuthenticatedVacasNumeroRoute
  AuthenticatedAnimalesIndexRoute: typeof AuthenticatedAnimalesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedVacunasRoute: AuthenticatedVacunasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnimalesNumeroRoute: AuthenticatedAnimalesNumeroRoute,
  AuthenticatedVacasNumeroRoute: AuthenticatedVacasNumeroRoute,
  AuthenticatedAnimalesIndexRoute: AuthenticatedAnimalesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
